### ISSUE TITLE
Error when saving edits

### ISSUE THREAD

**Issue by stephenwade** [acovrig/DatabaseProject#10] opened 2015-04-26 15:23 UTC
This occurs on BankAccount and Transaction (same pages as issue #5; could they be related?). I was unable to test on Payee because I can't find the Edit pages (trying `/Edit/{1..5}` didn't work here like it did on the others).

![image](https://cloud.githubusercontent.com/assets/4148577/7337853/b8bf0324-ec06-11e4-9595-a4fb55160272.png)

**Comment by acovrig** [comment] 2015-04-27 05:17
Duplicate of https://github.com/acovrig/DatabaseProject/issues/5

**Closed by acovrig** 2015-04-27 05:17 UTC
